# Generated by Django 5.0.4 on 2024-05-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
    ]
