# Generated by Django 5.0.4 on 2024-07-09 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
